### ISSUE TITLE
共同翻译 Laravel 5.1 文档

### ISSUE THREAD

**Issue by artiship** [golaravel/laravel5.1docs#1]
https://github.com/laravel/docs/pull/1623

**Comment by overtrue** [comment]
啥意思？

**Comment by artiship** [comment]
https://github.com/laravel-china/docs/issues/42#issuecomment-115578276

**Comment by wangsai** [comment]
能够有更多人参与文档翻译是好事，但是从我先前的经验来看，参与的人越多，质量越堪忧，因为无法保证每个参与者的经验、技术都比较好，势必为后期的 review 带来更多工作。

所以，laravel 5.1 的翻译工作我没有发帖子召集更多人参与，而是邀请了几个我了解的、使用 laravel 时间久的同学一起来翻译。

**Comment by artiship** [comment]
你说的有一定道理，不过我觉得英文文档本身不难懂，只要做过一些开发，就可以胜任，翻译三重境，信、达、雅，前两者讲求贴近原文，语句通顺。我看过你翻译的一些章节，你在有些地方怕读者看不懂，或省略、或加了一些自己的话，我觉得这些有待大家一起讨论，我比较倾向于贴近原文，对于补充的，可以放到博客和论坛中讨论。

从 5.1 发布初始，我们就开始了翻译，后来放到了 GitHub上，彼时 golaravel.com 和 laravel-china.org 还未开始翻译，我很欣赏你们之前做过的事情，大家都有自己的工作，还要无偿做这些事情，翻译是很花时间的，5.1 已经发布这么久了，你们两家网站上还没有完整的中文版文档，大家不应该各自己翻译，做重复的工作，现在让我们一起来做这个翻译吧

**Comment by artiship** [comment]
laravel-china.org 缺乏开放和友好的心态，我希望跟你们合作，整合已有的翻译，共同翻译还未翻译的章节，这样可以让 golaravel.com 上一点上线 5.1 的新文档

**Comment by wangsai** [comment]
非常欢迎。

关于翻译是紧贴原文还是多加一些注解，我个人还是倾向后者，毕竟文档就是为了辅助大家学习的，如果不把事情讲清楚，还要再去费力查找的话，就浪费时间了。当然，对于篇幅过长的补充知识给出引文链接即可（平时我们看到的纸板书也会对一些知识做注解）。

我看到 laragirl 仓库已经完成了不少翻译了，其中还有一点儿是将 laravel-taiwan 仓库中的翻译繁简转译过来的，这部分还是应该再校正一下，毕竟在一些措辞、语序上的差异是无法自动完成的。

**Comment by wangsai** [comment]
我已经向你发送邀请添加到这边的翻译组中了。

我建议这样：
- 两边同时把英文官方的文档同步到最新一次 commit，再将已翻译的部分合并
- 每章文档至少增加一个人做审校
- 对于繁简转换 laravel-taiwan 那边的文档，务必自己审校一遍，确保文档同步最新进度并且措辞合乎简中习惯

**Comment by artiship** [comment]
@wangsai 

我在翻译的过程已经对 laravel/docs 后续的 commits 作过多次合并，也就是说 laragirl/docs 已经是最新的，正如你所了解的，我们已经翻译了许多章节，基本上 golaravel 翻译过的章节我们也已经翻译了

所以我想与其我再将翻译合并到你的分支上，或者再创建一个新分支，都不如就是目前的分支上开展，你可以直接拉取 laragirl/docs 作为 5.1 的文档，laragirl 会是大家合作的结果，对于你说的 reviewer 的人员设定，我觉得非常有必要

很高兴加入 golaravel 可以一起做这些有意义的事情，我还有更进一步关于网站的想法，文档只是一部分。

**Comment by wangsai** [comment]
好！

后续尽量坚持每天合并一次 英文文档 。

你说的很对，没有必要浪费时间折腾两个仓库合并的工作，这样吧：
- 不管哪一方已经翻译的文档，都指定一个以上的人进行审校或兼有合并的审校，审校后的文档暂时分别提交到两个仓库。
- 清理任务分配，把还没有开展翻译的任务还原为未分配状态，每个参与翻译的人一次认领一个任务。
- 在任务列表标注每篇文档的审校者。

**Comment by lxalano** [comment]
我是来支持的！

**Comment by artiship** [comment]
It's awsome!

这当中涉及到非常多需要即时沟通的问题，例如译法，认领、提交、审校，我们翻译中有专门建一个QQ群 297473872，希望大家都加一下，然后更多的细节我们在群里面即时沟通。

**Comment by wangsai** [comment]
我觉得还是在 github 上留言更好，能够保存所有记录，也给后加入者提供更多信息。Q群一般是用来灌水的 :smiley:

**Comment by artiship** [comment]
如果是这样，要提交到两个地方，又在两个地方校验，问题会很多，效率也很低

我已邀请你加入 laragirl  的翻译组了，我觉得大家就在 laragirl/docs 下协作翻译，golaravel 可以 fork laragirl/doc,或者直接拉取 laragirl/docs 作为 5.1 文档显示到网站上，不必向两个地方提交

**Comment by wangsai** [comment]
laragirl/docs 上的文档有待审校和改进，暂时不考虑从 laragir/docs 直接拉取文档。

我说的是把最终审校后的文档提交到两个地方，工作量不大。

**Comment by johnlui** [comment]
反客为主？

From My iPhone

**Comment by wangsai** [comment]
我们会针对国内开发者学习、使用 laravel 时遇到的问题提供一些辅助方法，比如大家在安装 composer 以及 composer install 时遇到墙的问题，我们会提供一键安装包，这部分说明我会添加到文档中，帮助新进用户快速上手 laravel ，但是增加的这些文档是英文官方没有的，而且是和 golaravel 绑定的，可能不适合 laragirl。并且后续这些辅助方法还会继续增加。

再者，对同一份文档存在不同版本的翻译是完全可以的，而且可以互相取长补短，求同存异。

**Comment by wangsai** [comment]
laravel 5.0 文档我们就是直接采用 laravel-china/docs 的翻译，并且也把自己的翻译提交了过去，不存在门户之见。

但是 laravel-china/docs 是从 laravel-taiwan/docs 繁简转译过来的，还是有很多需要改进的地方，毕竟机械化的替换比不上人的智慧。这就是我前面提及的问题。

**Comment by artiship** [comment]
@johnlui 无所谓主客，若论主客，我以为我们直接 fork 的 laravel/docs 文档，及时更新，翻译尊重原文，目前翻译的章节最多，相比于 golaravel 自己创建的 repository, 进展缓慢，恐怕是我主你客吧？

何况我所说，是为了如何高效地协作，找到最佳办法

**Comment by artiship** [comment]
@wangsai packagist.org 国内已经可以正常访问，不需要一键安装包，你说的辅助方法当然是可以的，你可以放到文档之外的栏目，golaravel 可以出入门教程，然后将相关东西放进去，文档应该注重与原文一致，或者即使你要加，也应该注明一下，比如将你加的内容显示为蓝色

**Comment by artiship** [comment]
@wangsai 我不知道你们之前是这样做翻译的，甚至我都看过 laravel-taiwan/docs 有些翻译都存问题，如果直接转译，岂不更糟

**Comment by artiship** [comment]
我其实并无心再做第三个 laravel 门户同你们竞争，我觉得这个没有什么意义，若论 “Laravel 中文官网” 就应该像 laravel.tw 一样，不要加入太多自己的东西，那样想必愿意参与的人也会更多，这个也是为什么台湾那边的翻译进展得不错的原因，因为这个是中立的，我想做中立的，但已无时机，现在我们几方都来做这个事情，已经有点乱了，开发者都不知道哪个才是中文官网

我坚持想做这件事的原因是，我希望通过做这件事情，认识一些朋友，一起做点有意义的事，当然我也非常希望与各位结识，跟你们合作，向你们学习

最后，不知道你们现在可以有多少人来参与翻译，每个人每天可以投入多少时间呢？

**Comment by wangsai** [comment]
多研究些问题，少谈些“主义” － 胡适

**Comment by artiship** [comment]
多花点时间做翻译，少花点时间注册域名
